import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { NextAuthProvider } from "./sessionProvider";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const LoadingIndicator = () => <div>Loading...</div>;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <React.Suspense fallback={<LoadingIndicator />}>
            {children}
          </React.Suspense>
          <Toaster richColors position="bottom-center" />
        </NextAuthProvider>
      </body>
    </html>
  );
}
